/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  AggregatorMock,
  AggregatorMockInterface,
} from "../AggregatorMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161013c38038061013c83398101604081905261002f91610037565b60805261004f565b600060208284031215610048578081fd5b5051919050565b60805160d561006760003960006039015260d56000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c806350d25bcd1460375780638205bf6a14606b575b600080fd5b7f00000000000000000000000000000000000000000000000000000000000000005b60405190815260200160405180910390f35b605960006078606442607d565b905090565b600082821015609a57634e487b7160e01b81526011600452602481fd5b50039056fea2646970667358221220c51979727e53029790c726eb2fe6bb472ccca64c02e4a08b041175aefba979e964736f6c63430008040033";

export class AggregatorMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    answer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AggregatorMock> {
    return super.deploy(answer, overrides || {}) as Promise<AggregatorMock>;
  }
  getDeployTransaction(
    answer: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(answer, overrides || {});
  }
  attach(address: string): AggregatorMock {
    return super.attach(address) as AggregatorMock;
  }
  connect(signer: Signer): AggregatorMock__factory {
    return super.connect(signer) as AggregatorMock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AggregatorMockInterface {
    return new utils.Interface(_abi) as AggregatorMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AggregatorMock {
    return new Contract(address, _abi, signerOrProvider) as AggregatorMock;
  }
}
