/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AggregatorInterface,
  AggregatorInterfaceInterface,
} from "../AggregatorInterface";

const _abi = [
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AggregatorInterface__factory {
  static readonly abi = _abi;
  static createInterface(): AggregatorInterfaceInterface {
    return new utils.Interface(_abi) as AggregatorInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AggregatorInterface {
    return new Contract(address, _abi, signerOrProvider) as AggregatorInterface;
  }
}
