/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ImmutableOwner,
  ImmutableOwnerInterface,
} from "../ImmutableOwner";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_immutableOwner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "immutableOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161013238038061013283398101604081905261002f91610044565b60601b6001600160601b031916608052610072565b600060208284031215610055578081fd5b81516001600160a01b038116811461006b578182fd5b9392505050565b60805160601c60a561008d60003960006031015260a56000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80638ec7356814602d575b600080fd5b60537f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f3fea2646970667358221220fc9ccc196982020182c90f6b3a4cb6dc6386af843e7cbd334e7d199deeca808b64736f6c63430008040033";

export class ImmutableOwner__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _immutableOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ImmutableOwner> {
    return super.deploy(
      _immutableOwner,
      overrides || {}
    ) as Promise<ImmutableOwner>;
  }
  getDeployTransaction(
    _immutableOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_immutableOwner, overrides || {});
  }
  attach(address: string): ImmutableOwner {
    return super.attach(address) as ImmutableOwner;
  }
  connect(signer: Signer): ImmutableOwner__factory {
    return super.connect(signer) as ImmutableOwner__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImmutableOwnerInterface {
    return new utils.Interface(_abi) as ImmutableOwnerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImmutableOwner {
    return new Contract(address, _abi, signerOrProvider) as ImmutableOwner;
  }
}
