/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  InteractiveNotificationReceiver,
  InteractiveNotificationReceiverInterface,
} from "../InteractiveNotificationReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "taker",
        type: "address",
      },
      {
        internalType: "address",
        name: "makerAsset",
        type: "address",
      },
      {
        internalType: "address",
        name: "takerAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "makingAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "takingAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "interactiveData",
        type: "bytes",
      },
    ],
    name: "notifyFillOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class InteractiveNotificationReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): InteractiveNotificationReceiverInterface {
    return new utils.Interface(
      _abi
    ) as InteractiveNotificationReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InteractiveNotificationReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InteractiveNotificationReceiver;
  }
}
