/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  InteractiveNotificationReceiverMock,
  InteractiveNotificationReceiverMockInterface,
} from "../InteractiveNotificationReceiverMock";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "Received",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "takerAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "takingAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "interactiveData",
        type: "bytes",
      },
    ],
    name: "notifyFillOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061022e806100206000396000f3fe6080604052600436106100225760003560e01c8063cf21c7751461006657600080fd5b3661006157604080513381523460208201527f88a5966d370b9919b20f3e2c13ff65706f196a4e32cc2c12bf57088f88525874910160405180910390a1005b600080fd5b34801561007257600080fd5b50610086610081366004610145565b610088565b005b604051632e1a7d4d60e01b815260048101849052823560601c906001600160a01b03871690632e1a7d4d90602401600060405180830381600087803b1580156100d057600080fd5b505af11580156100e4573d6000803e3d6000fd5b50506040516001600160a01b038416925086156108fc02915086906000818181858888f1935050505015801561011e573d6000803e3d6000fd5b505050505050505050565b80356001600160a01b038116811461014057600080fd5b919050565b600080600080600080600060c0888a03121561015f578283fd5b61016888610129565b965061017660208901610129565b955061018460408901610129565b9450606088013593506080880135925060a088013567ffffffffffffffff808211156101ae578384fd5b818a0191508a601f8301126101c1578384fd5b8135818111156101cf578485fd5b8b60208285010111156101e0578485fd5b6020830194508093505050509295989194975092955056fea2646970667358221220f400b9473e6952d052ecac38fd74be73daa83793cc02f3d3e0638fb422187d4564736f6c63430008040033";

export class InteractiveNotificationReceiverMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<InteractiveNotificationReceiverMock> {
    return super.deploy(
      overrides || {}
    ) as Promise<InteractiveNotificationReceiverMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): InteractiveNotificationReceiverMock {
    return super.attach(address) as InteractiveNotificationReceiverMock;
  }
  connect(signer: Signer): InteractiveNotificationReceiverMock__factory {
    return super.connect(
      signer
    ) as InteractiveNotificationReceiverMock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InteractiveNotificationReceiverMockInterface {
    return new utils.Interface(
      _abi
    ) as InteractiveNotificationReceiverMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InteractiveNotificationReceiverMock {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as InteractiveNotificationReceiverMock;
  }
}
