/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IUniV3RangeOrder,
  IUniV3RangeOrderInterface,
} from "../IUniV3RangeOrder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "taker",
        type: "address",
      },
      {
        internalType: "address",
        name: "makerAsset",
        type: "address",
      },
      {
        internalType: "address",
        name: "takerAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "makingAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "takingAmount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "interactiveData",
        type: "bytes",
      },
    ],
    name: "notifyFillOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IUniV3RangeOrder__factory {
  static readonly abi = _abi;
  static createInterface(): IUniV3RangeOrderInterface {
    return new utils.Interface(_abi) as IUniV3RangeOrderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniV3RangeOrder {
    return new Contract(address, _abi, signerOrProvider) as IUniV3RangeOrder;
  }
}
