/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { NonceManager, NonceManagerInterface } from "../NonceManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "maker",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newNonce",
        type: "uint256",
      },
    ],
    name: "NonceIncreased",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "amount",
        type: "uint8",
      },
    ],
    name: "advanceNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "increaseNonce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "nonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "makerAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "makerNonce",
        type: "uint256",
      },
    ],
    name: "nonceEquals",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061022a806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806370ae92d21461005157806372c244a814610084578063c53a029214610099578063cf6fc6e3146100a1575b600080fd5b61007161005f366004610165565b60006020819052908152604090205481565b6040519081526020015b60405180910390f35b6100976100923660046101af565b6100de565b005b61009761013d565b6100ce6100af366004610186565b6001600160a01b03919091166000908152602081905260409020541490565b604051901515815260200161007b565b33600081815260208190526040812080547ffc69110dd11eb791755e4abd6b7d281bae236de95736d38a23782814be5e10db9260ff861692916101229084906101d0565b9182905550604051908152602001905060405180910390a250565b61014760016100de565b565b80356001600160a01b038116811461016057600080fd5b919050565b600060208284031215610176578081fd5b61017f82610149565b9392505050565b60008060408385031215610198578081fd5b6101a183610149565b946020939093013593505050565b6000602082840312156101c0578081fd5b813560ff8116811461017f578182fd5b600082198211156101ef57634e487b7160e01b81526011600452602481fd5b50019056fea2646970667358221220645aa1a7dcec6f52a5cf2ff251b533e5851ee0a9657800a51208458ece49a9f564736f6c63430008040033";

export class NonceManager__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NonceManager> {
    return super.deploy(overrides || {}) as Promise<NonceManager>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): NonceManager {
    return super.attach(address) as NonceManager;
  }
  connect(signer: Signer): NonceManager__factory {
    return super.connect(signer) as NonceManager__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NonceManagerInterface {
    return new utils.Interface(_abi) as NonceManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NonceManager {
    return new Contract(address, _abi, signerOrProvider) as NonceManager;
  }
}
