/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface AmountCalculatorInterface extends ethers.utils.Interface {
  functions: {
    "arbitraryStaticCall(address,bytes)": FunctionFragment;
    "getMakerAmount(uint256,uint256,uint256)": FunctionFragment;
    "getTakerAmount(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "arbitraryStaticCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMakerAmount",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTakerAmount",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "arbitraryStaticCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMakerAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTakerAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export class AmountCalculator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AmountCalculatorInterface;

  functions: {
    arbitraryStaticCall(
      target: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapTakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapMakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  arbitraryStaticCall(
    target: string,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMakerAmount(
    orderMakerAmount: BigNumberish,
    orderTakerAmount: BigNumberish,
    swapTakerAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTakerAmount(
    orderMakerAmount: BigNumberish,
    orderTakerAmount: BigNumberish,
    swapMakerAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    arbitraryStaticCall(
      target: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapTakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapMakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    arbitraryStaticCall(
      target: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapTakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapMakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    arbitraryStaticCall(
      target: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapTakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTakerAmount(
      orderMakerAmount: BigNumberish,
      orderTakerAmount: BigNumberish,
      swapMakerAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
